Feature/#24 마이페이지 구현
SW-CSS/sw-css pull request #101
Opened 2024-07-12 03:47 UTC by amaran-th

- close #24 
### 구현 내용
> 마이페이지 대시보드를 구현했습니다. 

<img width="1203" alt="image" src="https://github.com/user-attachments/assets/64fab89c-f39e-4f68-b44a-df200ff8c2e4">

### 리뷰 예상 소요시간 - `15분`

2024-07-12 06:29 UTC, llddang requested changes
수고하셨습니다

2024-07-12 06:29 UTC, llddang commented on frontend/src/app/(withSidebar)/my-page/components/MilestoneHistorySection/index.tsx
> +'use client';
여기에서 client component로 사용한 이유가 있을까요?
sever component로 충분히 변환가능해보입니다!

2024-07-12 06:29 UTC, llddang commented on frontend/src/app/(withSidebar)/my-page/components/MilestoneHistoryStatusLabel/index.tsx
> +      return <span className="rounded-sm bg-green-100 px-2 py-1 text-green-500">승인</span>;
전체적으로 상태의 글자 크기가 큰 것 같아서요.
색상으로도 충분한 정보가 들어온다고 생각되어서 글자 크기를 줄이는건 어떨까요?

2024-07-12 06:29 UTC, llddang commented on frontend/src/app/(withSidebar)/my-page/components/MilestoneSection/index.tsx
> +  // TODO - 컴포넌트 단위로 분리하기
지금하시는건 어떨까요!

2024-07-12 06:29 UTC, llddang commented on frontend/src/app/(withSidebar)/my-page/milestone/components/MilestoneHistoryTable/index.tsx
> +  size?: number;
size는 갯수보다는 크기를 의미하는 것 같습니다.
다른 단어를 사용하는 건 어떨까요?

2024-07-12 06:29 UTC, llddang commented on frontend/src/app/(withSidebar)/my-page/components/MilestoneSection/index.tsx
> +          <MilestoneHistoryTable searchFilterPeriod={searchFilterPeriod} size={5} />
옴 이 컴포넌트에서만 border 색상이 너무 진한 것 같습니다.
다른 컴포넌트랑 맞추는건 어떨까요?

2024-07-16 15:13 UTC, amaran-th commented on frontend/src/app/(withSidebar)/my-page/components/MilestoneHistorySection/index.tsx
> +'use client';
마이페이지를 구성하는 모든 Section 컴포넌트들은 로그인한 회원의 학번 정보를 통해 api를 호출해야 하는데, 이 학번을 불러오려면 useAppSelector 훅을 사용해야 해서 클라이언트 컴포넌트로 구현할 수밖에 없을 것 같습니다.!

2024-07-16 15:13 UTC, amaran-th commented on frontend/src/app/(withSidebar)/my-page/components/MilestoneHistoryStatusLabel/index.tsx
> +      return <span className="rounded-sm bg-green-100 px-2 py-1 text-green-500">승인</span>;
반영하였습니다!

2024-07-16 15:21 UTC, amaran-th commented on frontend/src/app/(withSidebar)/my-page/components/MilestoneSection/index.tsx
> +  // TODO - 컴포넌트 단위로 분리하기
생각해봤는데 이미 충분히 컴포넌트단위로 분리가 되어있는 것 같아서 그대로 두기로 했습니다!

2024-07-16 15:28 UTC, amaran-th commented on frontend/src/app/(withSidebar)/my-page/milestone/components/MilestoneHistoryTable/index.tsx
> +  size?: number;
백엔드 라이브러리에서는 페이지 번호와 크기에 대해 page와 size라는 이름을 쓰고 있어서 일관성을 맞춰주기 위해 사용했습니다!
페이지의 크기라는 의미에서는 size도 나쁘지 않은 것 같아요

2024-07-16 15:38 UTC, amaran-th commented on frontend/src/app/(withSidebar)/my-page/components/MilestoneSection/index.tsx
> +          <MilestoneHistoryTable searchFilterPeriod={searchFilterPeriod} size={5} />
border 컬러로 변경했습니다!

2024-07-18 06:31 UTC, llddang approved these changes
수고하셨습니다.

다른 사항은 없는데요. `MilestoneHistoryTableProps`의 변수명 한 번 만 봐주세요!

2024-07-19 10:26 UTC, amaran-th commented on frontend/src/app/(withSidebar)/my-page/components/MilestoneHistorySection/index.tsx
> +'use client';
id는 쿠키로부터 가져오기로 했고, 반영해서 서버컴포넌트로 변경했습니다!

2024-07-19 10:33 UTC, amaran-th commented on frontend/src/app/(withSidebar)/my-page/milestone/components/MilestoneHistoryTable/index.tsx
> +  size?: number;
page까지 해서 각각 pageNumber, pageSize로 변경했습니다!

2024-07-23 01:04 UTC, merged