Feature/#18 어드민 헤더 사이드바 푸터 설정
SW-CSS/sw-css pull request #28
Opened 2024-06-21 06:59 UTC by llddang

2024-06-21 22:01 UTC, amaran-th requested changes
수고하셨습니다! 코멘트 확인 부탁드려용

2024-06-24 00:51 UTC, llddang commented on frontend/src/adminComponents/Header/index.tsx
> +      { title: '학생 목록', url: '/admin/member', key: 'member-list' },
단순히 복수로 가는건 위의 대표 uri와 하위 uri (마일스톤의 경우 등록, 현황 페이지)와 다른 것이 어색한 것 같습니다.
`/admin/milestone`과 같이 대표 uri는 단수로 통일하고 그 하위에 목록 같은 경우는 `/admin/milestone/list`와 같이 가는게 어떨까요?

2024-06-24 01:02 UTC, amaran-th commented on frontend/src/adminComponents/Header/index.tsx
> +      { title: '학생 목록', url: '/admin/member', key: 'member-list' },
좋습니다! 노션 컨벤션에 추가해둘게요~!

2024-06-24 01:29 UTC, llddang commented on frontend/src/adminComponents/Header/styled.ts
> +'use client';
원래는 header안에서 훅을 사용하지 않으려고 했었는데.. 사용하면서 달라진 것 같습니다.
header 자체에서는 hook을 사용하지 않고 아래에 클라이언트 컴포넌트를 생성하도록 수정했습니당!

2024-06-24 01:33 UTC, llddang commented on frontend/src/app/(auth)/sign-in/page.tsx
> +/* eslint-disable react-hooks/exhaustive-deps */
훅에 누락된 종속성이 있을 때 뜨는 경고를 지우려고 했었습니다.

수정되기 전에 코드가 useEffect안에 종속되지 않은 변수를 사용해서 에러 문구가 뜨길래 추가해주었던 걸로 기억합니다.

지금은 필요없으니 삭제했습니당!

2024-06-24 01:33 UTC, llddang commented on frontend/src/app/styled.ts
> +import { ADMIN_HEADER_HEIGHT, ADMIN_SIDEBAR_WIDTH, COLOR, RESPONSIVE_WIDTH } from '@/constants';
좋습니다!

2024-06-24 04:25 UTC, llddang commented on frontend/src/adminComponents/Header/styled.ts
> +  background-color: ${COLOR.admin_point};
primary, secondary - light, main, dark로 통일하겠습니다!

2024-06-24 05:05 UTC, amaran-th approved these changes
사소한 코멘트 남겼습니다! 수고하셨습니다~!

2024-06-24 05:05 UTC, amaran-th commented on frontend/src/app/styled.ts
> +  min-height: calc(100vh - 200px);
200px 대신 상수화한 값을 사용하는 편이 더 좋을 것 같습니다!

2024-06-24 07:08 UTC, merged