Feature/#91 회원 계정 관리 페이지 구현
SW-CSS/sw-css pull request #96
Opened 2024-07-10 06:27 UTC by llddang

### 관련 이슈
- close #91 

### 작업 요약
- 회원 계정 관리 페이지 구현

### 리뷰 요구 사항
- 리뷰 예상 시간: `15분`

### 미리 보기
<img width="1436" alt="image" src="https://github.com/SW-CSS/sw-css/assets/77055208/d5920867-09f0-4244-a5a3-a1b18618c615">

2024-07-10 14:46 UTC, amaran-th requested changes
논의했으면 하는 점이 있어서 RC 날립니다~! 그 외에 크게 신경쓰이는 부분은 없네요
수고하셨습니다.

2024-07-10 14:46 UTC, amaran-th commented on frontend/src/app/admin/member/list/page.tsx
> +        query={JSON.stringify(searchParams)}
데이터의 페이지네이션 처리를 백엔드에서 할지 프론트엔드에서 할지 논의해보면 좋을 것 같아요!
백엔드에서 페이지네이션 처리를 하면 프론트에서는 page와 size 값만 넘겨주고 해당 페이지의 데이터들만 받아올 수 있는데, 이러면 넘겨받는 데이터의 양이 적기 때문에 성능상으로 이점이 있습니다. 프론트에서 처리해야 할 로직도 줄어들구요.

2024-07-10 15:31 UTC, amaran-th commented on frontend/src/types/common.dto.ts
> +  studentNumber: number;
DB 상으로 id가 학번이라서 이 속성은 필요가 없을 것 같습니다!

2024-07-12 06:49 UTC, llddang commented on frontend/src/app/admin/member/list/page.tsx
> +        query={JSON.stringify(searchParams)}
아마도 위의 slice 매서드 때문에 코드리뷰를 한 것 같은데요.
저도 당연히 백엔드에서 필요한 데이터만 주고 받을 것이라 생각합니다!

위의 slice는 현재 mocks 데이터에 많은 값들을 넣어주어서 임시로 이렇게 해놓은 것입니다!

2024-07-12 06:50 UTC, amaran-th commented on frontend/src/app/admin/member/list/page.tsx
> +        query={JSON.stringify(searchParams)}
확인했습니다!

2024-07-12 07:00 UTC, amaran-th approved these changes
수고하셨습니다!

2024-07-12 07:03 UTC, merged