Feature/#26 마일스톤 실적등록 페이지 구현
SW-CSS/sw-css pull request #99
Opened 2024-07-10 14:27 UTC by amaran-th

- close #26 
마일스톤 실적 등록 페이지, 마일스톤 실적 조회(삭제) 페이지를 구현했습니다.
<img width="1565" alt="image" src="https://github.com/SW-CSS/sw-css/assets/81465068/496c18d2-a69e-4100-9e32-f4de27293094">
<img width="1561" alt="image" src="https://github.com/SW-CSS/sw-css/assets/81465068/6f8a2f85-e147-485f-8ba8-bfc47b1a1e9b">

*DB의 rejectReason이 모두 null로 되어 있기 때문에 '반려' 상태의 반려 사유를 조회하려면 DB 값을 수정해주어야 합니다.

2024-07-12 05:28 UTC, llddang requested changes
수고하셨습니다. 

혹시 마일스톤 실적 페이지에서 마일스톤 카테고리를 선택하는 부분만 끝까지 안 채워져있더라구요.
다른 이유가 없다면 이것도 끝까지 채우는 건 어떨까요?

또한 DataPicker나 FileUploader와 같은 것은 브랜치를 나누어서 작업하는 것이 좋아보입니다!

2024-07-12 05:28 UTC, llddang commented on frontend/src/app/(withSidebar)/my-page/milestone/register/components/MilestoneHistoryTable/index.tsx
> +};
백엔드에서 정렬된 실적을 보내주는게 좋을 것 같아요!

2024-07-12 05:28 UTC, llddang commented on frontend/src/app/(withSidebar)/my-page/milestone/register/components/MilestoneHistoryTable/index.tsx
> +        },
api 재호출이 목적이라면 next js 의 revalidate를 사용하는 것이 좋아보입니다!

2024-07-12 05:28 UTC, llddang commented on frontend/src/app/(withSidebar)/my-page/milestone/register/components/MilestoneHistoryTable/index.tsx
> +              </button>
button을 따로 컴포넌트로 만들고, 그 컴포넌트 안에 클릭 이벤트에 대한 처리를 하면 MilestoneHistoryTable도 server component로 만들수 있을 것 같은데요.
혹시 어떻게 생각하나요?

2024-07-12 05:28 UTC, llddang commented on frontend/src/app/(withSidebar)/my-page/milestone/register/write/page.tsx
> +});
categoryId에 대한 검증로직이 빠진 것 같습니다

2024-07-12 05:28 UTC, llddang commented on frontend/src/app/(withSidebar)/my-page/milestone/register/write/page.tsx
> +                required
<img width="741" alt="image" src="https://github.com/user-attachments/assets/587b68f4-ef94-42b8-a4e9-0c3e7eff0c18">
`required` 속성을 사용하면 저희가 의도한 문구가 아닌 기본 문구가 보이게 됩니다.
혹시 TextInput의 isRequried를 의도한 걸까요?

2024-07-12 05:32 UTC, llddang requested changes

2024-07-12 05:32 UTC, llddang commented on frontend/src/app/(withSidebar)/my-page/milestone/register/write/page.tsx
> +});
file에 대한 검증 로직도 없는 것 같습니다!

2024-07-12 05:32 UTC, llddang commented on frontend/src/app/(withSidebar)/my-page/milestone/register/write/page.tsx
> +                required
<img width="924" alt="image" src="https://github.com/user-attachments/assets/b7b41ac9-f225-4fd2-b36f-b2e0fb5fd218">
<img width="920" alt="image" src="https://github.com/user-attachments/assets/7219eb67-6a2f-4fda-ab2d-a522e7161b53">
에러 문구가 있을 떄와 없을 때의 활동실적 width이 달라져서요.
혹시 동일하게 맞춰줄 수 있을까요?

2024-07-16 17:46 UTC, amaran-th commented on frontend/src/app/(withSidebar)/my-page/milestone/register/components/MilestoneHistoryTable/index.tsx
> +};
백엔드측 API 수정해서 PR 올렸습니다!
프론트 내 정렬 관련 코드는 삭제했어요

2024-07-16 17:50 UTC, amaran-th commented on frontend/src/app/(withSidebar)/my-page/milestone/register/components/MilestoneHistoryTable/index.tsx
> +        },
음 서버 컴포넌트라면 revalidate를 사용하는 것이 맞겠으나 리액트 쿼리를 사용할 수 있는 클라이언트 컴포넌트 환경에서는 리액트 쿼리의 방식을 따르는 게 더 나을 것 같습니다!

2024-07-16 17:51 UTC, amaran-th commented on frontend/src/app/(withSidebar)/my-page/milestone/register/write/page.tsx
> +});
milestoneId가 선택되려면 categoryId도 선택되어야 하는 관계이니 일부러 빼주었습니다!

2024-07-16 17:56 UTC, amaran-th commented on frontend/src/app/(withSidebar)/my-page/milestone/register/components/MilestoneHistoryTable/index.tsx
> +              </button>
혹시 useSelector를 사용하지 않고 memberId 값을 불러올 수 있는 방법이 있을까요?
현재로선 이것때문에 서버 컴포넌트로의 변환이 어려워보입니다.

2024-07-17 02:30 UTC, amaran-th commented on frontend/src/app/(withSidebar)/my-page/milestone/register/write/page.tsx
> +                required
반영했습니다~

2024-07-17 02:30 UTC, amaran-th commented on frontend/src/app/(withSidebar)/my-page/milestone/register/write/page.tsx
> +                required
반영해서 required 속성 삭제했습니다

2024-07-18 06:22 UTC, llddang commented on frontend/src/app/(withSidebar)/my-page/milestone/register/components/MilestoneHistoryTable/index.tsx
> +              </button>
저희가 redux에도 상태를 저장하는데요. 쿠키로도 저장을 해주고 있어요.

기존에는 redux만 사용하는 걸 생각했다가, 권한 분리 작업(학생 사용자의 어드민 페이지 접근 불가)를 처리해주기 위해 middleware를 작성하면서 쿠키에도 상태를 저장하게 되었습니다.

나중에 api를 통하여 권한 분리를 할 수 있다는 것을 알게되었는데요. 이미 쿠키의 상태를 사용하는 곳이 있어서요..
이부분 어떻게 할지 논의해봐야겠네요!

그래서 일단은 useSelector를 사용하지 않고도 정보를 불러올 수 있습니다.
위의 revalidate도 그 측면에서 서버컴포넌트로 사용할 수 있다는 말이었어요.

2024-07-19 10:13 UTC, amaran-th commented on frontend/src/app/(withSidebar)/my-page/milestone/register/components/MilestoneHistoryTable/index.tsx
> +              </button>
구현했습니다!

2024-07-20 09:17 UTC, llddang approved these changes
수고하셨습니다!

2024-07-23 00:55 UTC, merged